### ISSUE TITLE
[Question] Add "Name" as a Sort By option

### ISSUE THREAD

**Issue by artdirk** [Adobe-Marketing-Cloud/asset-share-commons#148]
One of our business teams would like to have the option to sort search results alphabetically by name within their Asset Share, and I noticed that this attribute is not available for configuration as a "sort by" option in the OOTB Asset Share search template.

Is this something that might be of value within the core Asset Share Commons code?

**Comment by davidjgonzalez** [comment]
@artdirk Are you trying to sort by node name or asset title? I expect you should be able to do this, however you’d need to update the damAssetLucene index to make the appropriate property ordered so it’s available in the sort component. 

Sorting is just driven by the order by query builder predicate so whatever that can handle, ASC can handle.

**Comment by artdirk** [comment]
@davidjgonzalez, that's a good question. I think the business would like to sort alphabetically by the asset name that's displayed on the cards, but it looks like the asset name might be derived differently based on the asset type?

**Comment by davidjgonzalez** [comment]
Correct - if the asset title label is using a computed property that “selects” different values to display, the. You can’t sort on that since you don’t know what property to tell oak to sort on. For this you’d want to overlay the card/list (or title computed property) so the title is always pulling from the same property, and the. Make sure that property index use is marked as orderable in damAssetLucene index.
