### ISSUE TITLE
Sling Model Caching resulting in excessive mem usage

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Marketing-Cloud/asset-share-commons#177]
Sling Models cache=true attribute appears to be consuming extra memory netting a negative performance impact overall. (Internal issue code: NPR-23178)

The suggestion is to remove cache=true on all ASC Sling Model declarations.

The underlying issue requires adjustments to Sling.

**Comment by szymonkrzysztyniak** [comment]
Do you know when new version may be released (1.4.10)? We are struggling with memory leak on our PROD env and we are hoping to get this fixed with Sling Models Impl update.

**Comment by davidjgonzalez** [comment]
This is fixed in 1.5.0+

**Comment by paul-bjorkstrand** [comment]
Maybe to help add more information to this situation:

I recently started running into a similar memory issue in my project (I am not using this tool, just got here via Google searches). After doing some heap dump analysis, along with with code analysis, it appears that the issue is indeed caused by the issue @justinedelson posted above.

I have an (untested) theory, that the following sling model paradigm is the primary use case that triggers the issue in [SLING-7586](https://issues.apache.org/jira/browse/SLING-7586):
```java
@Self
SlingHttpServletRequest self
```

Looking at a heap dump after an OOM error, I saw many live instances of `SlingHttpServletRequest`, which, to me, was odd, since their life cycle should be quick, and they should not be held for much longer than the request itself. The common pattern in all of my model instances that were being held in memory was the circular reference caused by using `@Self`, as demonstrated above.

Aside from abolishing caching altogether, if the sling models were to clear any `@Self` annotated fields at the end of `@PostConstruct` methods, by setting them to null, the issue _should_ be successfully worked around. I will be doing this in my project's code and seeing if it resolves the issue, but I do recommend taking a similar approach and testing it. I imagine that a similar issue can occur with any kind of `@Self`, but since request objects are much larger than other adaptables, caching with request can cause OOM faster than other adaptables.

Ultimately, SLING-7586 needs to be fixed to completely resolve the issue, but I feel my approach is a more palatable alternative to saying "don't cache all the things"

@davidjgonzalez as a side note, you noted that this issue is fixed in 1.5.0+, when it is only fixed in 1.5.2+ I figured you would want to know of the typo :-)
