### ISSUE TITLE
How we can override the form-data.js  in extended project

### ISSUE THREAD

**Issue by anoopkumargarg** [Adobe-Marketing-Cloud/asset-share-commons#210]
I am trying to override /apps/asset-share-commons/clientlibs/clientlib-site/js/form-data.js file in my extended project but still original one is getting loaded. Could you please suggect what steps i need to do.

We have extended our project using this one only https://github.com/godanny86/sample-assetshare

**Comment by davidjgonzalez** [comment]
Sorry for the delay :(

you could try creating a custom client library folder and use "replace" to override the ASC delivered one. (i dont recall i replace was introduced in 6.3 or 6.4, so you'd want to check that). You can always reference the untouched ASC JS files via absolute path.

I dont think there is a way you can append to the existing clientlib and overwrite (i assume you'd start getting double-loading).

I would be careful about doing this since the JS is a bit more fragile -- if this is something that generally makes sense we could look at pulling it into the main code line (it would need to be backwards compat of course) -- this is of course the simplest/safest approach.
