### ISSUE TITLE
[AEM 6.4] Newly created metadata schema properties do not show up in the Property Name dropdown 

### ISSUE THREAD

**Issue by arpithaar** [Adobe-Marketing-Cloud/asset-share-commons#231]
The Metadata Schema Properties Data source is not picking up the newly created metadata properties

AEM Version: 6.4
Asset Share Commons Version: 1.6.2
Run mode: Author

1. Configure a new property in the metadata schema editor (http://localhost:4502/mnt/overlay/dam/gui/content/metadataschemaeditor/schemadetails.html/default?formPath=/conf/global/settings/dam/adminui-extension/metadataschema&pickable=)
2. Go to Details Page(http://localhost:4502/editor.html/content/asset-share-commons/en/light/details.html/content/dam/asset-share-commons/en/public/pictures/alex-holyoake-157978.jpg)
2. Double Click on any metadata component in the edit mode
3. Scroll to find the newly created metadata property in the "Property Name" dropdown

Observation : The newly created metadata property  is not available in the dropdown

**Expected behavior**
The newly created metadata property  needs to be available in the dropdown

**Comment by Shaihuludus** [comment]
I have the same problem with search components. Create schema with metadata but Tags Filter component doesn't allows to select custom metadata

**Comment by godanny86** [comment]
@Shaihuludus this should be fixed with https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/232. It is not part of a release yet, just merged into the develop branch. Can you deploy develop and verify that it fixes your issue as well?

**Comment by Shaihuludus** [comment]
Hi I found the problem
ResourceType was used to filter metadata available in dialog dropdown but AEM keeps this information in two other properties not in resourceType.
There was a bug when checking for metadata types. They are stored in two different properties not in resource type.

Without this fix only fast properties where displayed when metadataFieldTypes="[tags]" (or any other then tags)  was used in dialog. 

https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/236 here is the fix

There is still problem with fastProperties because they are not filtered and always all of them are available in dropdown. However it is different issue for different fix

**Comment by godanny86** [comment]
Thanks for the PR @Shaihuludus will review shortly!

**Comment by Shaihuludus** [comment]
I had to close previous pr (to not add more code from fork) And this one is from branch only for this problem https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/238
