### ISSUE TITLE
Created Date is coming large than modified date on detail page in metadata section

### ISSUE THREAD

**Issue by anoopkumargarg** [Adobe-Marketing-Cloud/asset-share-commons#235]
**Describe the bug**
Created Date is coming large than modified date on detail page in metadata section

**Environment**
* AEM Version: AEM 6.3+SP2
* Asset Share Commons Version: 
* Author, Publish or both: Publish

**To Reproduce**
Upload an asset on Author instance
Replicate the asset after two days
Check the difference on asset detail page of that asset 

**Expected behavior**
Created Date should be smaller than modified date on detail page in metadata section

**Screenshots**

**Additional context**

**Comment by godanny86** [comment]
@anoopkumargarg do you mind attaching some screenshots so we have a better idea of the issue? I'm wondering if this is related to how the jcr:created property is treated during replication from an Author to Publish instance...

**Comment by davidjgonzalez** [comment]
@anoopkumargarg I expect this is because your Metadata Components are pulling from `[dam:Asset]/jcr:created` and  `[dam:Asset]/jcr:content/jcr:lastModified`...

These are JCR properties and represent when the actual nodes were created/modified in the JCR vs "true" metadata about the asset. `jcr:created` property is "re-created" when the dam:Asset node is created upon replication, where as the `jcr:content/jcr:lastModified` is not triggered, thus the modified date (sourced via the value set on AEM Author) is after the jcr:created date (set by AEM publish).

I think you'd need to set other metadata properties that represent these values to reliably report on them... but i suggest you ensure these values represent what the users of the system expect them to represent.. for example, are these intended to represent when the underlying binary asset was created/modified? when the asset was created in AEM? When the metadata of the Asset was updated?

That being said, i can see the confusion since in the sample ui.content ASC package these properties are used for Created and Modified (perhaps we should remove them).

**Comment by davidjgonzalez** [comment]
Labeling as `wontfix` not because we wouldn't want to remedy this, but because the way these properties work is defined by AEM, and we can't change that. If there is a reasonable work-around we could implement in ASC to help w this, let's re-open and make it happen!
