### ISSUE TITLE
metadataFieldTypes does not filter data source for Date Range and Tag Filters

### ISSUE THREAD

**Issue by godanny86** [Adobe-Marketing-Cloud/asset-share-commons#242]
**Describe the bug**
The metadataFieldTypes property, when set on a property filter dialog, has the effect of showing only FastProperties in the filter dialog drop-down. However, this does not seem to be the intention of this property.  It is currently undocumented and the behavior is unclear.

**Environment**
* AEM Version: 6.4
* Asset Share Commons Version: 1.6.2
* Author, Publish or both? Author

**To Reproduce**
1. Open the dialog of the Tag Filter or Date Range filter
2. Click the dialog property dropdown and view only the fast properties...

**Expected behavior**
Expect the dropdown to just show DateTime or tags respectively

**Screenshots**
On the Date Range Dialog `metadataFieldTypes="[datetime]` but shows only fastProperties, including properties that are not date/times.
![image](https://user-images.githubusercontent.com/8974514/44632145-eaae6200-a943-11e8-9c9b-33cde7e8ad98.png)

On the Tag Filter Dialog `metadataFieldTypes="[tags]"` also shows only fastProperties, including properties that are not tags.
![image](https://user-images.githubusercontent.com/8974514/44632161-2c3f0d00-a944-11e8-9252-a8dd0683a107.png)

**Additional context**
This is related to some observations in issue #231

**Comment by godanny86** [comment]
Thanks @Shaihuludus.

@davidjgonzalez do you recall the motivation behind the deltaFastProperties?

**Comment by davidjgonzalez** [comment]
IIRC its because the datasource first lists all Properties that are enumerated in the Metadata Schemas (so the Metadata Schema definition is the boundary for which fast properties are put into the dropdown list)... however there may be fast properties that (which means they're listed in the index, so ostensibly they're "important"), that DONT have metadata scheme entries (for example, the dam:size which outputs "junk" values (bytes) OOTB) .. however these "fast" properties that ARE indexed, but NOT in metadata schema's are prime(?) candidates for searching (again, because someone, product/customer took the time to put them into a search index).

I believe the delta properties show at the bottom of the dropdown as well, and don't have a "Label", just the relative property path.

Perhaps we could add another PN on the datasource widget that dictates if these should be included or not?

**Comment by Shaihuludus** [comment]
They for sure appear at the top,. mixed with other fast properties.

**Comment by davidjgonzalez** [comment]
@Shaihuludus ah yes, my memory isn't so good - they all go into the same TreeMap which sorts them as equals - which of course is easy enough to change.

It seems reasonable to have the datasource respect the `metadataFieldTypes` better ... ie, if `metadataFieldTypes` is set, then skip the delta's (since we can't tell what `metadataFieldTypes` a property is from just the index, and someone specifically specified the `metadataFieldTypes` they want)

**Comment by Shaihuludus** [comment]
Sorry for delay 
https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/238 has the change as we discussed. Delta fast properties are at the end of the list and only when there is no metadata type provided in component.

I didn't want to mix with treemap (and sorting) so I added a new icon for delta properties which will put them at the end of the list
