### ISSUE TITLE
Default sorting representation

### ISSUE THREAD

**Issue by Shaihuludus** [Adobe-Marketing-Cloud/asset-share-commons#255]
Hi, 
Is there a possibility to represent default sorting from search results in sort component?

**Comment by davidjgonzalez** [comment]
@Shaihuludus IIRC this one was tricky for 2 reasons...

1) the variant of the SemanticUI dropdown control used. IIRC marking an option as selected, does not make it show in the label; you'd have to work some extra logic in that goes a step further than the "usual" `getInitialValue()` logic, and print out the label. Using the dropdown's in semantic that don't use the js and are just the select boxes help reduce this complexity, but this would change how these dropdowns actually look.

2) the orderby or orderby sort can be sourced from the search component config and not query params. Ie. ?orderby.sort=desc  .. but there is no orderby in the request params, so sourced server-side from the search component. Prior to #249's SearchConfig abstraction (which "finds" the right resources on the page), there wasn't a good way for other components (ie. the Sort component) to get other component's values (which is generally good since component-coupling is brittle -> bad; though the Search Results component is required which is why its the exception to the rule).

So there's some of the history of why it doesn't do it today :) that being said - its certainly possible, and likely requires a refactor of the SortPredicateImpl to 

1. leverage SearchConfig to get default values
2. set the label variables used in HTL, based on the getInitialValue()
