### ISSUE TITLE
Search bar results not proper with partial and wild card search

### ISSUE THREAD

**Issue by assetshare2018** [Adobe-Marketing-Cloud/asset-share-commons#369]
**Describe the bug**
Hi Team,
Search bar is having some issue with below scenarios
1.	Partial Search
Users are unable to search the asset using partial search option. for example, user searched for "00044000057701" in search bar which is mapped in metadata property, it will give the results. But in some case if they search for "44000057701" as a partial search, it’s not showing any results.
2.	Wild card Search with Special character
there is an asset with property value “40100-Nilla12356.tif” and user searched for *Nilla12* keyword with wild card, it will give the results. But if we search using *00-Nilla12* keyword with wild card & Special character, it’s not showing any results.

**Environment**
* AEM Version: 6.3.2
* Asset Share Commons Version: 1.5.2
* Author, Publish or both?: Both

**To Reproduce**
1. upload a file name called "40100-Nilla12356.tif" and add metadata property as "00044000057701".
2. Now Search for "00044000057701" in asset share commons search bar which is mapped in metadata property, it will give the results. But in some case if they search for "44000057701" as a partial search, it’s not showing any results.
3. Wild card Search with Special character, search for *Nilla12* keyword with wild card, it will give the results. But if we search using *00-Nilla12* keyword with wild card & Special character, it’s not showing any results.

**Expected behavior**
we are expecting results during wild card search with special character and partial search.

**Comment by davidjgonzalez** [comment]
@assetshare2018 can you verify you get the expected results in AEM Omnisearch on AEM Author?

I believe this is how Lucene fulltext search is implemented.

**Comment by davidjgonzalez** [comment]
See images below for the first use case showing this is how OOTB fulltext search works as well:

![image](https://user-images.githubusercontent.com/1451868/52919534-5b21b480-32d1-11e9-946e-29aedb3a29c7.png)

![image](https://user-images.githubusercontent.com/1451868/52919543-6ffe4800-32d1-11e9-9b68-b5c448c16d85.png)

Wrt to your 2nd use case, this is expected because AEM search splits on "-" .. so when you have a node name of: `40100-Nilla12356.tif` it is split into 3 discrete terms `40100`, `Nilla12356`, `tif`.

So `*00-Nilla12*` will not match because the searchable term was split into 2 terms (`40100`, `Nilla12356`). If you Search for `*00` OR `Nilla12*` you get results.

You can test all this out in OOTB AEM Omnisearch.

Closing as this is how OOTB AEM Search and the OOTB QueryBuilder Fulltext Predicate [1] work. 

[1] https://helpx.adobe.com/experience-manager/6-4/sites/developing/using/querybuilder-predicate-reference.html#fulltext
