### ISSUE TITLE
Issues with public CVEs (Security vuln report)

### ISSUE THREAD

**Issue by vivekm2017** [Adobe-Marketing-Cloud/asset-share-commons#391]
**Describe the bug**
Component governance has reported 5 issues with POM dependency on org.apache.felix:org.apache.felix.http.jetty version 3.4.2:

- CVE-2017-7656
- CVE-2017-7657
- CVE-2017-7658
- CVE-2017-9735
- CVE-2018-12536

"In Eclipse Jetty, versions 9.2.x and older, 9.3.x (all configurations), and 9.4.x (non-default configuration with RFC2616 compliance enabled), transfer-encoding chunks are handled poorly. The chunk length parsing was vulnerable to an integer overflow. Thus a large chunk size could be interpreted as a smaller chunk size and content sent as chunk body could be interpreted as a pipelined request. If Jetty was deployed behind an intermediary that imposed some authorization and that intermediary allowed arbitrarily large chunks to be passed on unchanged, then this flaw could be used to bypass the authorization imposed by the intermediary as the fake pipelined request would not be interpreted by the intermediary as a request."

**Environment**
* AEM Version: 6.3
* Asset Share Commons Version: 1.6.10
* Author, Publish or both?: Both

**To Reproduce**
-Run the component compliance CVE on any project using Asset share commons bundle as dependency.

**Expected behavior**
Upgrade dependency for org.apache.felix:org.apache.felix.http.jetty to version 4.0.8 in bundle POM.

**Screenshots**
NA

**Additional context**
More Details around the security issue: https://www.securitytracker.com/id/1041194

**Comment by davidjgonzalez** [comment]
@vivekm2017 Jetty is a dependency provided BY AEM, no AEM project (much less this one) would provide a version of jetty. Checking my AEM 6.5, it appears it exports 4.0.7 (ie. it does not use 4.0.8) - also, keep in mind we support AEM back to AEM 6.3 SP1 for now, so all those need to be accommodated.

Have you logged a ticket with Adobe Support about the version of jetty shipped with AEM? This project has to align w/ whatever AEM exports, so this "issue" can't be fixed in this project. 

Please re-open this ticket if Adobe Support can provide guidance on this.

**Comment by davidjgonzalez** [comment]
@vivekm2017 I notice you asked the same question on the ACS AEM Commons project [1]. The same thinking applies as well-explained by @justinedelson - there's nothing we can do about which version of jetty AEM ships, and we deploy to AEM, so we must target the versions exported by AEM. Youll need to log an Adobe Support ticket for them to upgrade Jetty.


[1] https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1799
