### ISSUE TITLE
Newsletter shows blurry on the Asset Share Page

### ISSUE THREAD

**Issue by oscar-cami** [Adobe-Marketing-Cloud/asset-share-commons#403]
**Describe the bug**
An image of format .psd  with the following resolution 750x5150 is activated from the author and published onto the Asset Share Page. The image thumbnail narrows down the image and shows it blurry. I would expect that the image is cut in order to display it correctly instead of squeezing the height in order to fit it into the preview box.

**Environment**
* AEM Version: 6.4.3
* Asset Share Commons Version: 1.7.0
* Author, Publish or both? Publish

**To Reproduce**
1. Go to Author Instance and upload an image with a proportion of 1x7 (width x height)
2. Activate the image to Publish it
3. Go to Publish instance and see how it looks like
4. See error: Image height has been resized in order to fit the complete image into the preview box.

**Expected behavior**
I would expect that the preview shows correctly and cuts the image however is necessary in order to fit it and display the correct proportions.

**Screenshots**
![image](https://user-images.githubusercontent.com/48984928/56490326-17bc1000-64e5-11e9-8090-d1a4a71dcf9b.png)
![image](https://user-images.githubusercontent.com/48984928/56490334-23a7d200-64e5-11e9-98e0-13a8e88de423.png)

**Comment by davidjgonzalez** [comment]
I imagine its because the Thumbnail is used to render this image, which IIRC is 319px in the longest dimension, which means the thumbnail image that is driving this card is 17pixels wide.

The default style on the card is to cover the card, which results in upscaling from 17px wide to ~260px wide (which is the default card width).

I think any way you cut it, a 17px wide preview is ~useless - youll probably need to either update how the OOTB thumbnail rendition is generated or customize the Card results layout to source from an asset rendition that makes sense for your assets. Keep in mind - ideally you dont want to be loading massive images as the thumbnails as this may slow down the end user experience.
