### ISSUE TITLE
Rating feature implementation for Assets

### ISSUE THREAD

**Issue by assetshare2018** [Adobe-Marketing-Cloud/asset-share-commons#406]
Do we have rating feature in Asset Share commons, and if not any future plan?
Thanks in advance!

**Comment by davidjgonzalez** [comment]
Nope - Ratings support (by end-users) doesn't exist, and no plans. One of the biggest issues is we don't have a good way to store and propagate/sync user-generated content across AEM instances (Publish's and Author).

AEM Author's UI has ratings which you can set in AEM Author's UI, however, there is no component to surface them, and no plans to create one since it's seldom used; ratings tend to be more useful when provided by end-users, vs authors.
