### ISSUE TITLE
Default sorting fails when Statistics component is rendered before results container

### ISSUE THREAD

**Issue by cornsen** [Adobe-Marketing-Cloud/asset-share-commons#430]
**Describe the bug**
When the Statistics component is rendered before the result component, the default layout setting is not applied from the result components configuration.

**Environment**
* AEM Version: 6.4.1
* Asset Share Commons Version: 1.7.0
* Both

**To Reproduce**
1. Go to search page (light.html)
2. Move Statistics component inside the layoutcontainer above the resultcontainer
3. Change default layout to "LIST" in results component.

**Expected behavior**
The statistics component seems to initialize the search model and applies it to a modelcache. As the initialisation is resource based, it doesn't find a "layout" property at the statistics component...therefore the default "CARD" layout is selected.

When the resultcontainer is rendered it gets the initialized version from the modelcache with the wrong layout property.

**Screenshots**
-N/A-

**Additional context**
When adding a jcr property to the statistics component with layout="list", the result will be initially in listview.

**Comment by godanny86** [comment]
ah very interesting. Yes I can reproduce the bug:

![image](https://user-images.githubusercontent.com/8974514/59702079-ca3de580-91ab-11e9-9967-06ba1d889636.png)

**Comment by davidjgonzalez** [comment]
@cornsen this https://github.com/Adobe-Marketing-Cloud/asset-share-commons/pull/431 should fix it... the problem was we "cache" the search results..  so the first component to "get" the search results sling model, is the instance that is cached (we don't want to run the same query multiple times per page). .. The trick is when that model is created in the context of the statistics component (or really any component NOT the search results, none of the expected properties are on the "resource"; since the resource is the statistics component). 

To get around the problem (which first ran into with Sorting IIRC) we had to make a "SearchConfig" abstraction that is smart enough to go find the Search Results component and expose all those data points from the "correct" resource (that of the search results component itself).

Thanks for catching and explaining the error so nicely though! took more time to write this comment than fix the issue (i hope!) :P

**Comment by cornsen** [comment]
Hi David, thank you for the fast response and fix! Looking forward for the next release.

**Comment by godanny86** [comment]
@cornsen if you don't mind I'll keep this open until its in a release

**Comment by davidjgonzalez** [comment]
@godanny86 nice label!! 👨‍🎓
