### ISSUE TITLE
Framework question

### ISSUE THREAD

**Issue by niks1020** [Adobe-Marketing-Cloud/asset-share-commons#446]
**How does the QuerySearchProviderImpl.java gets called internally?**
* I am quiet new to AEM and its framework and having hard time to find any call of the above mentioned class or its parent interface anywhere in the asset share commons code?
* All I know is that this implementation gets called when the search page gets loaded, but don't know how? Because I cannot trace that there is any servlet call configuration of any kind. Its just that the class is annotated with @Component and its parent interface SearchProvider.java is annotated with @ConsumerType.

I know this is a very basic and kind of framework question, then asset share commons specific question, so can somebody (while answering my above question) also suggest me any tutorial or youtube channel for such basic thing.

**Comment by godanny86** [comment]
Hi @niks1020 great question!

So Asset Share Commons like other AEM implementations tries to use Sling Models as much as possible when feeding an HTL component. An ajax call is ultimately responsible for calling the search results but if looking at say the search results rendered as a card: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/ui.apps/src/main/content/jcr_root/apps/asset-share-commons/components/search/results/result/card/card.html#L43 *Note the idea of a model cache is something that is unique to ASC in order to prevent multiple queries being run for the same search result request*

Here you can see a reference to: com.adobe.aem.commons.assetshare.search.Search: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/search/Search.java and the implementation: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/search/impl/SearchImpl.java#L91 where you can see the result method loops through any registered SearchProviders. Finally, https://github.com/Adobe-Marketing-Cloud/asset-share-commons/blob/develop/core/src/main/java/com/adobe/aem/commons/assetshare/search/providers/impl/QuerySearchProviderImpl.java#L64 implements the SearchProvider interface. These multiple levels of abstraction were added so that implementations could register their own SearchProvider implementations and override the one provided by ASC.



For something pretty basic about how Sling Models work I'd recommend: https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/custom-component.html. I also recommend ACS Samples: https://adobe-consulting-services.github.io/acs-aem-samples/ it is a fantastic resource put together by @davidjgonzalez.

**Comment by developer-avenger** [comment]
Hi @godanny86 ,

Following up on this thread, I am trying to write a custom Search Provider. But it is not getting registered. I always see QuerySearchProviderImpl in OSGI Components. Not sure what I am missing. Below is the signature or my custom search provider.

@Component(service = SearchProvider.class, immediate = true, property = {
		Constants.SERVICE_DESCRIPTION + "=Custom Search Provider",
		Constants.SERVICE_RANKING + ":Integer=" + Integer.MIN_VALUE })
public class CustomSearchProviderImpl implements SearchProvider {
