### ISSUE TITLE
What is maximum repository size asset share query will work?

### ISSUE THREAD

**Issue by vineeth522** [Adobe-Marketing-Cloud/asset-share-commons#459]
Does asset share search query will give decent performance for large repositories(around 30 TB)?  
What is maximum repository size asset share search built to support?

**Comment by davidjgonzalez** [comment]
@vineeth522 There is no limit based on the repository size. Any "limits" would be in the Oak index size (# of records) and the queries performed against them. 

Generally,  important performance characteristics of queries are based on the number of matching results (or candidate results).  There are some details involving guessTotal and Limits (ie. pagination) that make handling even super-large result sets performant.

The two main causes of performance degradation in ASC are:

1) Not configuring your damAssetLucene index to match any custom filtering/sorting. For example, if you want to sort on a custom property "releaseDate", and you do not mark this property as orderable in your damAssetLucene index definition, then the query will likely be slow for large result sets (since it sorts in memory). ASC provides guardrails around this, for example by only allowing Orderable properties to be selected in the Sort by component, as well as showing Fast (lightning) and Slow (turtle) icons next to Filter properties. Ideally the properties you "configure" in the Search components are all "fast" (meaning they are backed by an index rule in damAssetLucene)

2) Using post-query QB filters against super-large results sets. Some query restrictions cannot be represented by native JCR-SQL2 queries, so QueryBuilder will "post-process" the results in memory, removing results that do not match. If the query engine returns 1MM results, and the first 900k need to get filtered out, then this query will be slow (since it has to iterate over 900k records before finding the first one). That said, this is seldom a problem IRL because having properly qualified query restrictions (see #1 above) are in place to help ensure the results form the QueryEngine are not super-large.  If this case is ever hit, its normally easy to resolve by adding other filtering parameters that reduce the super-large result set before it hits in-memory filtering. 

HTH
