### ISSUE TITLE
Need to update asset share publish download size to 10 GB.

### ISSUE THREAD

**Issue by preetsekhon94** [Adobe-Marketing-Cloud/asset-share-commons#481]
**Question?**
* What piece of functionality do you have a question about?
* What are you trying to achieve?

Documentation can be found here: https://adobe-marketing-cloud.github.io/asset-share-commons/. It might answer your question!
 
Hi,

We have a requirement where we need to update asset share publish site's download size to 10GB. Could you please suggest how we can achieve this.

Regards,
Lovepreet

**Comment by davidjgonzalez** [comment]
@preetsekhon94  please review the docs for this:

https://adobe-marketing-cloud.github.io/asset-share-commons/pages/actions/download/#update-maxcontentsize-for-the-assetdownloadservlet

Please re-open w/ details if this doesnt answer your Q.

**Comment by preetsekhon94** [comment]
Hi David,

Thanks for the update. I have just one query as mentioned in below step:

"Create a new OSGi Configuration named com.day.cq.dam.core.impl.servlet.AssetDownloadServlet in the config.publish.nosamplecontent folder."

So here asset share commons downlaod servlet path should be given or the downlaodservlet which we have overridden in our project that path should be given in configuration?

Regards,
Lovepreet

**Comment by davidjgonzalez** [comment]
@preetsekhon94 not sure i follow.. the max size configuration is specifically for the OOTB `com.day.cq.dam.core.impl.servlet.AssetDownloadServlet` so you would just define the properties in the OSGi configuration as described in the ASC docs (linked above).

If you have a *custom* (overriding) Download Servlet you are hitting, then I'm not sure what you need to do, since i don't know what/how that was implemented. I'd talk to the developer of that customer/override servlet and figure out how it works and what the appropriate method for overriding would be (if all it does proxies back to OOTB, then you might be able to simply apply the OOTB configurations..?)
