### ISSUE TITLE
No restriction on Sort by options ( Note : Suggestion )

### ISSUE THREAD

**Issue by chinny-biztech** [Adobe-Marketing-Cloud/asset-share-commons#54]
According to the current setup, there is no limitation on number of sort by options. Isn't it good to limit this in multi-field? eg: maxMultifieldLimit = "5" 
This may help the query optimisation process in large extent. If the author accidentally configures number of sort by options more than usual  , it may lead to critical performance issues in the instance.

**Comment by davidjgonzalez** [comment]
@chinny-biztech What exactly are you talking about? The Sort By component's dialog simply specifies the OPTIONS that can be made available to sort results. The end-user can only select ONE option at time.

For example, they can NOT sort by Last Modified THEN Created THEN Title .. they can only choose ONE to sort by at a time.

It doesnt matter how many options are available as long a) they are optimized for sorting (which they are due to the property selection restriction) and b) one sort order is applied at a time.

Note that the properties available for sorting (via the dialog) or limited to the those in `damAssetLucene` that are marked with `ordered=true` ensuring they are optimized for sorting.

If i am misunderstanding something please re-open with more info and why you believe this could lead to critical performance issues.

**Comment by chinny-biztech** [comment]
Hi @davidjgonzalez , thanks for the explanation. Yes I agree with you.

**Comment by raj2017selva** [comment]
getting the below error

*ERROR* [qtp53145845-2706] org.apache.felix.http.jetty %bundles.pluginTitle: Cannot start (org.osgi.framework.BundleException: Unable to resolve com.adobe.aem.commons.assetshare.core [542](R 542.4): missing requirement [com.adobe.aem.commons.assetshare.core [542](R 542.4)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.wcm.core.components.models.form)(version>=14.1.0)(!(version>=15.0.0))) [caused by: Unable to resolve com.adobe.cq.core.wcm.components.core [517](R 517.1): missing requirement [com.adobe.cq.core.wcm.components.core [517](R 517.1)] osgi.wiring.package; (&(osgi.wiring.package=com.day.cq.wcm.api.policies)(version>=1.6.0)(!(version>=2.0.0)))] Unresolved requirements: [[com.adobe.aem.commons.assetshare.core [542](R 542.4)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.wcm.core.components.models.form)(version>=14.1.0)(!(version>=15.0.0)))])
org.osgi.framework.BundleException: Unable to resolve com.adobe.aem.commons.assetshare.core [542](R 542.4): missing requirement [com.adobe.aem.commons.assetshare.core [542](R 542.4)] osgi.wiring.package; (&(osgi.wiring.package=co
