### ISSUE TITLE
Total values in asset share common statistics component

### ISSUE THREAD

**Issue by geravishal87** [Adobe-Marketing-Cloud/asset-share-commons#549]
Hi Team,
In below asset share component
asset-share-commons/components/search/statistics 
we a statistics html file
/apps/asset-share-commons/components/search/statistics/statistics.html
which gives runningtotal and total properties.

Total property  is actually giving the guess total values, it doesn't give the exact total count of assets. Is there a way that we can get exact total count also?

**Comment by davidjgonzalez** [comment]
See docs here: 

https://adobe-marketing-cloud.github.io/asset-share-commons/pages/search/results/

I believe there is a hard allowed maxvalue for guessTotal of 10,000. 

So you can increase the guessTotal and youll get accurate results UP to that number - be very careful as this can significantly impact performance though. So performance test against your largest possible result sets. It is NOT recommended to make this number large due to potential performance impact.
